#!/usr/bin/env bash
#script that displays numbers from 1 to 20 using while and case

a=1
while [ "$a" -lt 21 ]; do
  # if the value is 4:bad luck
   case "$a" in
     4) echo "$a"
           echo "bad luck from China"
            ;;
	 9) echo "$a"
             echo "bad luck from Japan"
		 ;;
	     17) echo "$a"
		  echo "bad luck from Italy"
		;;

		*)
		echo "$a"
              ;;
	esac

		((a++))
     done
