#!/usr/bin/env bash
#script thatdisplay the time for 12hrs and 59 min

hour=0
 while [ "$hour" -le 12 ]; do
  echo "Hour: $hour"
  minute=1
 while [ "$minute" -lt 60 ]; do
  echo "$minute"
   minute=$((minute + 1))
    done
  hour=$((hour+1))
 done
